//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeTranstechWS.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="V_PO", Namespace="http://schemas.datacontract.org/2004/07/TranstechWS")]
    [System.SerializableAttribute()]
    public partial class V_PO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BSARTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EBELNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EBELPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LGOBEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LGORTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LGPBEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MAKTXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MATNRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MEINSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MENGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MENGE2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BSART {
            get {
                return this.BSARTField;
            }
            set {
                if ((object.ReferenceEquals(this.BSARTField, value) != true)) {
                    this.BSARTField = value;
                    this.RaisePropertyChanged("BSART");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EBELN {
            get {
                return this.EBELNField;
            }
            set {
                if ((object.ReferenceEquals(this.EBELNField, value) != true)) {
                    this.EBELNField = value;
                    this.RaisePropertyChanged("EBELN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EBELP {
            get {
                return this.EBELPField;
            }
            set {
                if ((object.ReferenceEquals(this.EBELPField, value) != true)) {
                    this.EBELPField = value;
                    this.RaisePropertyChanged("EBELP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LGOBE {
            get {
                return this.LGOBEField;
            }
            set {
                if ((object.ReferenceEquals(this.LGOBEField, value) != true)) {
                    this.LGOBEField = value;
                    this.RaisePropertyChanged("LGOBE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LGORT {
            get {
                return this.LGORTField;
            }
            set {
                if ((object.ReferenceEquals(this.LGORTField, value) != true)) {
                    this.LGORTField = value;
                    this.RaisePropertyChanged("LGORT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LGPBE {
            get {
                return this.LGPBEField;
            }
            set {
                if ((object.ReferenceEquals(this.LGPBEField, value) != true)) {
                    this.LGPBEField = value;
                    this.RaisePropertyChanged("LGPBE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MAKTX {
            get {
                return this.MAKTXField;
            }
            set {
                if ((object.ReferenceEquals(this.MAKTXField, value) != true)) {
                    this.MAKTXField = value;
                    this.RaisePropertyChanged("MAKTX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MATNR {
            get {
                return this.MATNRField;
            }
            set {
                if ((object.ReferenceEquals(this.MATNRField, value) != true)) {
                    this.MATNRField = value;
                    this.RaisePropertyChanged("MATNR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MEINS {
            get {
                return this.MEINSField;
            }
            set {
                if ((object.ReferenceEquals(this.MEINSField, value) != true)) {
                    this.MEINSField = value;
                    this.RaisePropertyChanged("MEINS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MENGE {
            get {
                return this.MENGEField;
            }
            set {
                if ((this.MENGEField.Equals(value) != true)) {
                    this.MENGEField = value;
                    this.RaisePropertyChanged("MENGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MENGE2 {
            get {
                return this.MENGE2Field;
            }
            set {
                if ((this.MENGE2Field.Equals(value) != true)) {
                    this.MENGE2Field = value;
                    this.RaisePropertyChanged("MENGE2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="V_MIGO", Namespace="http://schemas.datacontract.org/2004/07/TranstechWS")]
    [System.SerializableAttribute()]
    public partial class V_MIGO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ENTRY_QNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MATERIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PLANTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_ITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_NUMBERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STGE_LOCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ENTRY_QNT {
            get {
                return this.ENTRY_QNTField;
            }
            set {
                if ((this.ENTRY_QNTField.Equals(value) != true)) {
                    this.ENTRY_QNTField = value;
                    this.RaisePropertyChanged("ENTRY_QNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MATERIAL {
            get {
                return this.MATERIALField;
            }
            set {
                if ((object.ReferenceEquals(this.MATERIALField, value) != true)) {
                    this.MATERIALField = value;
                    this.RaisePropertyChanged("MATERIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PLANT {
            get {
                return this.PLANTField;
            }
            set {
                if ((object.ReferenceEquals(this.PLANTField, value) != true)) {
                    this.PLANTField = value;
                    this.RaisePropertyChanged("PLANT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_ITEM {
            get {
                return this.PO_ITEMField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_ITEMField, value) != true)) {
                    this.PO_ITEMField = value;
                    this.RaisePropertyChanged("PO_ITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_NUMBER {
            get {
                return this.PO_NUMBERField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_NUMBERField, value) != true)) {
                    this.PO_NUMBERField = value;
                    this.RaisePropertyChanged("PO_NUMBER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STGE_LOC {
            get {
                return this.STGE_LOCField;
            }
            set {
                if ((object.ReferenceEquals(this.STGE_LOCField, value) != true)) {
                    this.STGE_LOCField = value;
                    this.RaisePropertyChanged("STGE_LOC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="V_BAPIRETURN", Namespace="http://schemas.datacontract.org/2004/07/TranstechWS")]
    [System.SerializableAttribute()]
    public partial class V_BAPIRETURN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIELDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOG_MSG_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOG_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGE_V1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGE_V2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGE_V3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGE_V4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMBERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PARAMETERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ROWField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZSYSTEMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIELD {
            get {
                return this.FIELDField;
            }
            set {
                if ((object.ReferenceEquals(this.FIELDField, value) != true)) {
                    this.FIELDField = value;
                    this.RaisePropertyChanged("FIELD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOG_MSG_NO {
            get {
                return this.LOG_MSG_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.LOG_MSG_NOField, value) != true)) {
                    this.LOG_MSG_NOField = value;
                    this.RaisePropertyChanged("LOG_MSG_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOG_NO {
            get {
                return this.LOG_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.LOG_NOField, value) != true)) {
                    this.LOG_NOField = value;
                    this.RaisePropertyChanged("LOG_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MESSAGE {
            get {
                return this.MESSAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGEField, value) != true)) {
                    this.MESSAGEField = value;
                    this.RaisePropertyChanged("MESSAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MESSAGE_V1 {
            get {
                return this.MESSAGE_V1Field;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGE_V1Field, value) != true)) {
                    this.MESSAGE_V1Field = value;
                    this.RaisePropertyChanged("MESSAGE_V1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MESSAGE_V2 {
            get {
                return this.MESSAGE_V2Field;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGE_V2Field, value) != true)) {
                    this.MESSAGE_V2Field = value;
                    this.RaisePropertyChanged("MESSAGE_V2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MESSAGE_V3 {
            get {
                return this.MESSAGE_V3Field;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGE_V3Field, value) != true)) {
                    this.MESSAGE_V3Field = value;
                    this.RaisePropertyChanged("MESSAGE_V3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MESSAGE_V4 {
            get {
                return this.MESSAGE_V4Field;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGE_V4Field, value) != true)) {
                    this.MESSAGE_V4Field = value;
                    this.RaisePropertyChanged("MESSAGE_V4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMBER {
            get {
                return this.NUMBERField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMBERField, value) != true)) {
                    this.NUMBERField = value;
                    this.RaisePropertyChanged("NUMBER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PARAMETER {
            get {
                return this.PARAMETERField;
            }
            set {
                if ((object.ReferenceEquals(this.PARAMETERField, value) != true)) {
                    this.PARAMETERField = value;
                    this.RaisePropertyChanged("PARAMETER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ROW {
            get {
                return this.ROWField;
            }
            set {
                if ((this.ROWField.Equals(value) != true)) {
                    this.ROWField = value;
                    this.RaisePropertyChanged("ROW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TYPE {
            get {
                return this.TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.TYPEField, value) != true)) {
                    this.TYPEField = value;
                    this.RaisePropertyChanged("TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZSYSTEM {
            get {
                return this.ZSYSTEMField;
            }
            set {
                if ((object.ReferenceEquals(this.ZSYSTEMField, value) != true)) {
                    this.ZSYSTEMField = value;
                    this.RaisePropertyChanged("ZSYSTEM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITranstech")]
    public interface ITranstech {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranstech/ZMM_TRANSTECH_GET_PO", ReplyAction="http://tempuri.org/ITranstech/ZMM_TRANSTECH_GET_POResponse")]
        ConsumeTranstechWS.ServiceReference1.V_PO[] ZMM_TRANSTECH_GET_PO(int subrc, ref string MessageReturn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranstech/ZMM_TRANSTECH_MIGO", ReplyAction="http://tempuri.org/ITranstech/ZMM_TRANSTECH_MIGOResponse")]
        string ZMM_TRANSTECH_MIGO(ConsumeTranstechWS.ServiceReference1.V_MIGO[] Migo_items, ref ConsumeTranstechWS.ServiceReference1.V_BAPIRETURN[] Bapi_results, string TestRun, string Pstng_date, string Doc_date, string Header_txt, ref string MessageReturn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITranstechChannel : ConsumeTranstechWS.ServiceReference1.ITranstech, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TranstechClient : System.ServiceModel.ClientBase<ConsumeTranstechWS.ServiceReference1.ITranstech>, ConsumeTranstechWS.ServiceReference1.ITranstech {
        
        public TranstechClient() {
        }
        
        public TranstechClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TranstechClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranstechClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranstechClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsumeTranstechWS.ServiceReference1.V_PO[] ZMM_TRANSTECH_GET_PO(int subrc, ref string MessageReturn) {
            return base.Channel.ZMM_TRANSTECH_GET_PO(subrc, ref MessageReturn);
        }
        
        public string ZMM_TRANSTECH_MIGO(ConsumeTranstechWS.ServiceReference1.V_MIGO[] Migo_items, ref ConsumeTranstechWS.ServiceReference1.V_BAPIRETURN[] Bapi_results, string TestRun, string Pstng_date, string Doc_date, string Header_txt, ref string MessageReturn) {
            return base.Channel.ZMM_TRANSTECH_MIGO(Migo_items, ref Bapi_results, TestRun, Pstng_date, Doc_date, Header_txt, ref MessageReturn);
        }
    }
}
